config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resource :locator, only: [:show]

  get '/:user/dashboard', to: "users#show", as: :dashboard

  resources :crags, only: [:index, :new, :create, :show]

  namespace :admin do
    resources :crags, only: [:index, :edit, :destroy, :update]
    resources :users, only: [:index, :edit, :destroy]
  end
  namespace :api do
    namespace :v1 do
      resources :crags, defaults: { format: 'json' } do
      end
    end
  end
end

app/models/crag.rb
class Crag < ActiveRecord::Base
  validates_presence_of :location, :name, :description, :directions
  after_commit :clear_cache

  def clear_cache
    Rails.cache.clear
  end
end

app/models/panorama.rb
class Panorama < ActiveRecord::Base
  belongs_to :user
  after_commit :clear_cache

  def clear_cache
    Rails.cache.clear
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :panoramas

  def self.from_omniauth(auth)
    where(uid: auth[:uid]).first_or_create do |user|
      user.uid = auth.uid
      user.provider = auth.provider
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.profile_image = auth.info.image
    end
    refresh_panoramas(auth[:uid])
    return User.find_by(uid: auth[:uid])
  end

  def self.refresh_panoramas(uid)
    user = User.find_by(uid: uid)
    user.panoramas = []
    XMLParser.create_users_panoramas(uid)
  end

  def admin?
    self.role == 1
  end
end

app/models/xml_parser.rb
class XMLParser
  def self.create_users_panoramas(uid)
    user = User.find_by(uid: uid)
    service = PicasaService.new
    panoramas = service.get_geo_album(uid)

    if panoramas
      panoramas.each do |panorama_data|
        user.panoramas << Panorama.create(
        location: XMLParser.format_location(panorama_data["where"]["Point"]["pos"]),
        thumbnail: panorama_data["content"]["src"]
        )
      end
    end
  end

  def self.format_location(location)
    location.gsub(/\s/, " " => ",")
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/admin/crags_controller.rb
class Admin::CragsController < Admin::BaseController
  def index
    @crags = Crag.all
  end

  def edit
    @crag = Crag.find(params["id"])
  end

  def destroy
    Crag.destroy(params["id"])
    redirect_to request.referrer
  end

  def update
    @crag = Crag.find(params["id"])
    @crag.update(crag_params)
    if @crag.save
      redirect_to admin_crags_path(current_user)
    else
      flash[:error] = @crag.errors.full_messages.join(", ")
    end
  end

  private

  def crag_params
    params.require(:crag).permit(:name, :description, :directions, :location)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def destroy
    User.destroy(params["id"])
    redirect_to request.referrer
  end
end

app/controllers/api/v1/crags_controller.rb
class Api::V1::CragsController < ApplicationController
  respond_to :json

  def create
    respond_with :api, :v1, Crag.create(crag_params)
  end

  private

  def crag_params
    params.require(:crag).permit(:name, :description, :directions, :location)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/crags_controller.rb
class CragsController < ApplicationController
  def index
    @crags = Crag.all
  end

  def new
    @crag = Crag.new
    @location = params["location"]
  end

  def create
    @crag = Crag.new(crag_params)
    if @crag.save
      flash[:notice] = "Successfully added #{@crag.name} to our database!"
      redirect_to crags_path(@crag)
    else
      flash[:error] = @crag.errors.full_messages.join(", ")
      redirect_to request.referrer
    end
  end

  def show
    @crag = Crag.find(params["id"])
  end

  private

  def crag_params
    params.require(:crag).permit(:name, :description, :directions, :location)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @crags = Crag.all
  end
end

app/controllers/locators_controller.rb
class LocatorsController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    flash[:success] = "Signed in as #{user.name}!"
    redirect_to dashboard_path(user)
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully Signed Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/crags/edit.html.erb
 <h1><%= "Edit #{@crag.name}" %></h1>

<%= form_for @crag, url: admin_crag_path, method: :patch do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name, placeholder: "#{@crag.name}" %>
  <%= f.label "Description" %>
  <%= f.text_area :description, placeholder: "#{@crag.description}" %>
  <%= f.label "Directions" %>
  <%= f.text_area :directions, placeholder: "#{@crag.directions}" %>
  <%= f.hidden_field :id, value: @crag.id %>
  <%= f.submit "Update Crag" %>
<% end %>

app/views/admin/crags/index.html.erb
<% @crags.each do |crag| %>
  <tr class="crag-<%= crag.id %>">
    <td><%= crag.name %></td>
    <td><%= link_to "Delete", admin_crag_path(crag), method: :delete %></td>
    <td><%= link_to "Edit", edit_admin_crag_path(crag) %></td>
  </tr>
<% end %>

app/views/admin/users/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>User ID</th>
      <th>User Name</th>
      <th>Delete</th>
      <th>Edit</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% unless user.admin? %>
        <tr class="user-<%= user.id %>">
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Delete", admin_user_path(user), method: :delete %></td>
        </tr>
      <% end %>
    <% end %>
</tbody>

app/views/crags/index.html.erb
<%= render partial: "layouts/crag_table" %>

app/views/crags/new.html.erb
<div class="container well">
  <p>Fill out the fields beneath to tell our users a bit about this area.
    Once you click "Create Crag" your listing go be live on the CragView database!</p>
</div>

<%= render partial: "layouts/view", locals: {location: @location} %><br>
<div class="container">
  <div class="new-crag-form">
    <%= form_for @crag do |f| %>
      <%= f.text_area :name, placeholder: "Name" %>
      <%= f.text_area :description, placeholder: "Description" %>
      <%= f.text_area :directions, placeholder: "Directions" %>
      <%= f.hidden_field :location, value: @location %>
      <%= f.submit "Create Crag", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/crags/show.html.erb
<div class="crag-info">
<div class="well">
  <%= @crag.name %><br>
</div>
<%= render partial: "layouts/view", locals: {location: @crag.location} %><br>
  <div class="well container">
    Description: <%= @crag.description %><br>
  </div>
  <div class="well container">
    Directions: <%= @crag.directions %><br>
  </div>
</div>

app/views/home/show.html.erb
<body class="landing">
  <div class="home text-center">
    <div class="container">
      <a class="btn btn-primary" href="/crags" role="button">View All Crag Views</a>
    </div><br>
    <div class="container">
      <a class="btn btn-primary" href="/auth/google_oauth2" role="button">Sign In To Add Your Views</a>
    </div>
  </div>
</body>

app/views/layouts/_crag_table.html.erb
<div class="crag-table">
  <% if @crags %>
      <table class="table table-bordered" id="crag-table">
        <thead>
          <tr>
            <th>Crag Name</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <% cache("crags list") do %>
            <% @crags.each do |crag| %>
            <tr>
              <td> <%= link_to crag.name, crag_path(crag) %> </td>
              <td> <%= crag.description %> </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
  <% end %>
</div>

app/views/layouts/_js_map.html.erb
<%= javascript_tag do %>
  function initMap() {
    var mapDiv = document.getElementById('map');
    var map = new google.maps.Map(mapDiv, {
      center: {lat: 39.682808, lng: -105.982996},
      zoom: 8
    });

    var thePanorama = map.getStreetView();

    streetviewChangeListener = google.maps.event.addListener(thePanorama, 'visible_changed', function() {
                view_location = thePanorama.getPosition();
                console.log('streetview panorama position: ' + view_location);
      });
  }
<% end %>

<div id="map">
   <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS'] %>&callback=initMap"
       async defer></script>
</div>

app/views/layouts/_map.html.erb
<iframe width="900" height="500" frameborder="0" style="border:0" src= "<%= "https://www.google.com/maps/embed/v1/streetview?key=#{ENV["GOOGLE_MAPS"]}&location=40.0053998,-105.4064189&pitch=10" %>"></iframe>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= crags_path %>">CragView</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<li class="nav-item">
					<% if current_user %>
					<%= link_to "Sign Out", signout_path, id: "sign_out" %>
          <li class="nav-item"><%= link_to "Dashboard", dashboard_path(current_user) %></li>
					 <% else %>
						 <%= link_to "Sign in with Google to add your CragViews", "/auth/google_oauth2", id: "sign_in" %>
					 <% end %>
				</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to "Crag Locator", locator_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_view.html.erb
<div class="container view-container">
  <iframe width="75%" height="400" frameborder="0" style="border:0" src= "<%= "https://www.google.com/maps/embed/v1/streetview?key=#{ENV['GOOGLE_MAPS']}&location=#{location}&pitch=10" %>"></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CragView</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render "layouts/navbar" %>

    <% flash.each do |type, message| %>
      <div class="panel panel-default">
        <div class="panel-body"><%= "#{message}" %></div>
      </div>
    <% end %>

    <div class="ajax-flash"></div>
    <%= yield %>
  </body>
</html>

app/views/locators/show.html.erb
<div class="container well">
  <p>Drag and drop the "Pegman" to any location that you would like to create a new crag.
    Once you find a view to your liking, fill out the fields beneath to tell our users a bit about this area.
    Once you click "Create Crag" your listing go be live on the CragView database!</p>
</div>

<%= render partial: "layouts/js_map" %>

<div class="container">
  <div class="container map-form">
    <%= text_area_tag "Name", "Name"  %>
    <%= text_area_tag "Description", "Description"  %>
    <%= text_area_tag "Directions", "Directions"  %>
    <button id="create-crag" name="create-crag" class="btn btn-default pull-right">Create Crag</button>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.admin? %>
  <%= link_to "View All Crags", admin_crags_path(@user) %>
  <%= link_to "View All Users", admin_users_path(@user) %>
<% end %>
<div class="container well dashboard-panel">
<h1>Welcome <%= @user.name %> </h1>
  <p>
    <img src="<%= @user.profile_image %>" class="profile" height=100px width=100px >
    Thanks for being a part of the CragView community! There are two ways to add panoramas to the CragView database.
    <li>Browse Google Maps for StreetViews uploaded by any user <%= link_to "here", locator_path %>.</li>
    or
    <li>Select one of your panoramas from below</li>
  </p>
</div>
<% cache("user panoramas") do %>
  <% @user.panoramas.each do |panorama| %>
    <div class="container well">
      <p class="panorama-thumbnail"><%= link_to image_tag(panorama.thumbnail), {:controller => "crags", :action => "new", :location => panorama.location }, class: "thumbnail-#{panorama.id}" %><br></p>
    </div>
  <% end %>
<% end %>